"""empty message

Revision ID: 902a28924146
Revises: 9bc33ed9e8d7
Create Date: 2021-11-21 14:53:58.159410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902a28924146'
down_revision = '9bc33ed9e8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
