"""empty message

Revision ID: a3394b675ee9
Revises: 9fcba870ef10
Create Date: 2021-11-16 11:24:23.449535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3394b675ee9'
down_revision = '9fcba870ef10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_orders_id', table_name='product_orders')
    op.drop_table('product_orders')
    op.drop_constraint('customers_account_id_fkey', 'customers', type_='foreignkey')
    op.drop_column('customers', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('customers_account_id_fkey', 'customers', 'accounts', ['account_id'], ['id'])
    op.create_table('product_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='product_orders_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_orders_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_orders_pkey')
    )
    op.create_index('ix_product_orders_id', 'product_orders', ['id'], unique=False)
    # ### end Alembic commands ###
