"""empty message

Revision ID: 1567e4425bf3
Revises: 902a28924146
Create Date: 2021-11-21 15:12:09.757189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1567e4425bf3'
down_revision = '902a28924146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distributors', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distributors', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
