"""empty message

Revision ID: 08d14b38064e
Revises: 6f6872f9d32b
Create Date: 2021-11-16 09:24:55.996718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d14b38064e'
down_revision = '6f6872f9d32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracted_brands')
    op.drop_table('brand_products')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='purchase_orders_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='purchase_orders_product_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name='purchase_orders_pkey')
    )
    op.create_table('brand_products',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='brand_products_brand_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='brand_products_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'brand_id', name='brand_products_pkey')
    )
    op.create_table('contracted_brands',
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distributor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='contracted_brands_brand_id_fkey'),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], name='contracted_brands_distributor_id_fkey')
    )
    # ### end Alembic commands ###
