"""empty message

Revision ID: 2bf973012c67
Revises: e45a1f802599
Create Date: 2021-11-16 10:21:43.006972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf973012c67'
down_revision = 'e45a1f802599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_orders', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('product_orders', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_orders', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('product_orders', 'id')
    # ### end Alembic commands ###
