"""empty message

Revision ID: 3f72c1c061b0
Revises: c43d54cbcc46
Create Date: 2021-11-16 18:26:33.924960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f72c1c061b0'
down_revision = 'c43d54cbcc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_contractors',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('brand_id', 'distributor_id')
    )
    op.create_table('brand_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'brand_id')
    )
    op.drop_constraint('accounts_customer_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'customers', ['id'], ['id'])
    op.drop_column('accounts', 'customer_id')
    op.create_unique_constraint(None, 'customers', ['name'])
    op.drop_column('orders', 'processing_date')
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text("nextval('products_id_seq'::regclass)"))
    op.drop_constraint('products_description_key', 'products', type_='unique')
    op.create_unique_constraint(None, 'products', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.create_unique_constraint('products_description_key', 'products', ['description'])
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('products_id_seq'::regclass)"))
    op.add_column('orders', sa.Column('processing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='unique')
    op.add_column('accounts', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_customer_id_fkey', 'accounts', 'customers', ['customer_id'], ['id'])
    op.drop_table('brand_products')
    op.drop_table('brand_contractors')
    # ### end Alembic commands ###
