"""empty message

Revision ID: 896cd5cfed9b
Revises: 272a220787d1
Create Date: 2021-11-16 11:38:18.641624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896cd5cfed9b'
down_revision = '272a220787d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_customer_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'customers', ['id'], ['id'])
    op.drop_column('accounts', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_customer_id_fkey', 'accounts', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###
