"""empty message

Revision ID: 2fa0b1e7b443
Revises: 049aa3174241
Create Date: 2021-11-16 10:55:39.531148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa0b1e7b443'
down_revision = '049aa3174241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_orders_id'), 'product_orders', ['id'], unique=False)
    op.drop_column('product_orders', 'creationDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_orders', sa.Column('creationDate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_product_orders_id'), table_name='product_orders')
    # ### end Alembic commands ###
