"""empty message

Revision ID: 2e4d9c19b812
Revises: 3dd3e776d8ea
Create Date: 2021-11-14 16:54:37.492060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4d9c19b812'
down_revision = '3dd3e776d8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_constraint('brands_company_key', 'brands', type_='unique')
    op.create_unique_constraint(None, 'brands', ['name'])
    op.drop_column('brands', 'company')
    op.add_column('customers', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    op.add_column('distributors', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_constraint('distributors_company_key', 'distributors', type_='unique')
    op.create_unique_constraint(None, 'distributors', ['name'])
    op.drop_column('distributors', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributors', sa.Column('company', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'distributors', type_='unique')
    op.create_unique_constraint('distributors_company_key', 'distributors', ['company'])
    op.drop_column('distributors', 'name')
    op.add_column('customers', sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('customers', 'name')
    op.add_column('brands', sa.Column('company', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'brands', type_='unique')
    op.create_unique_constraint('brands_company_key', 'brands', ['company'])
    op.drop_column('brands', 'name')
    # ### end Alembic commands ###
