"""empty message

Revision ID: f71c64add923
Revises: 2e4d9c19b812
Create Date: 2021-11-14 20:19:18.151572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71c64add923'
down_revision = '2e4d9c19b812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('address', sa.String(length=100), nullable=False))
    op.drop_column('brands', 'address_line_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('address_line_1', sa.VARCHAR(length=75), autoincrement=False, nullable=False))
    op.drop_column('brands', 'address')
    # ### end Alembic commands ###
