"""empty message

Revision ID: 290e90d4853d
Revises: 2fa0b1e7b443
Create Date: 2021-11-16 11:03:18.094866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290e90d4853d'
down_revision = '2fa0b1e7b443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customers', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'account_id')
    # ### end Alembic commands ###
