"""empty message

Revision ID: 1f03cf1e6c01
Revises: 3f72c1c061b0
Create Date: 2021-11-16 18:27:19.361618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f03cf1e6c01'
down_revision = '3f72c1c061b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_contractors',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('brand_id', 'distributor_id')
    )
    op.create_table('brand_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'brand_id')
    )
    op.drop_constraint('accounts_customer_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'customers', ['id'], ['id'])
    op.drop_column('accounts', 'customer_id')
    op.create_unique_constraint(None, 'customers', ['name'])
    op.drop_column('orders', 'processing_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('processing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='unique')
    op.add_column('accounts', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_customer_id_fkey', 'accounts', 'customers', ['customer_id'], ['id'])
    op.drop_table('brand_products')
    op.drop_table('brand_contractors')
    # ### end Alembic commands ###
