"""empty message

Revision ID: 46f7a61a0107
Revises: 0100dd620883
Create Date: 2021-11-21 13:34:07.951016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f7a61a0107'
down_revision = '0100dd620883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accounts', 'customers', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'brand_id')
    # ### end Alembic commands ###
