"""empty message

Revision ID: 3dd3e776d8ea
Revises: bef6d50bbb6b
Create Date: 2021-11-14 16:39:13.933819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd3e776d8ea'
down_revision = 'bef6d50bbb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'zipcode')
    op.drop_column('brands', 'city')
    op.drop_column('brands', 'country')
    op.drop_column('brands', 'address_line_2')
    op.add_column('customers', sa.Column('address', sa.String(length=75), nullable=False))
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'address_line_1')
    op.drop_column('customers', 'zipcode')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'address_line_2')
    op.add_column('distributors', sa.Column('address', sa.String(length=75), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributors', 'address')
    op.add_column('customers', sa.Column('address_line_2', sa.VARCHAR(length=75), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('country', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('zipcode', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('address_line_1', sa.VARCHAR(length=75), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('city', sa.VARCHAR(length=90), autoincrement=False, nullable=False))
    op.drop_column('customers', 'address')
    op.add_column('brands', sa.Column('address_line_2', sa.VARCHAR(length=75), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('country', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('brands', sa.Column('city', sa.VARCHAR(length=90), autoincrement=False, nullable=False))
    op.add_column('brands', sa.Column('zipcode', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
