"""empty message

Revision ID: 049aa3174241
Revises: 2bf973012c67
Create Date: 2021-11-16 10:35:30.908737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049aa3174241'
down_revision = '2bf973012c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_orders')
    # ### end Alembic commands ###
