"""empty message

Revision ID: 9bc33ed9e8d7
Revises: 46f7a61a0107
Create Date: 2021-11-21 13:35:05.115947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc33ed9e8d7'
down_revision = '46f7a61a0107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_brand_id_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'brand_id')
    op.add_column('orders', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'customers', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'brand_id')
    op.add_column('accounts', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('accounts_brand_id_fkey', 'accounts', 'customers', ['brand_id'], ['id'])
    # ### end Alembic commands ###
