"""empty message

Revision ID: e45a1f802599
Revises: 08d14b38064e
Create Date: 2021-11-16 10:13:43.894690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45a1f802599'
down_revision = '08d14b38064e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('creationDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.drop_constraint('orders_brand_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'brand_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_brand_id_fkey', 'orders', 'brands', ['brand_id'], ['id'])
    op.drop_table('product_orders')
    # ### end Alembic commands ###
