"""empty message

Revision ID: f29d3f030946
Revises: a5185f4bb62b
Create Date: 2021-11-14 13:44:25.555190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29d3f030946'
down_revision = 'a5185f4bb62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_contracts',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('brand_id', 'product_id')
    )
    op.create_table('brand_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'brand_id')
    )
    op.create_table('purchase_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.add_column('accounts', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accounts', 'customers', ['customer_id'], ['id'])
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'brands', ['brand_id'], ['id'])
    op.add_column('parcels', sa.Column('estimated_delivery_date', sa.DateTime(timezone=20), nullable=True))
    op.add_column('parcels', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('parcels', sa.Column('distributor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'parcels', 'distributors', ['distributor_id'], ['id'])
    op.create_foreign_key(None, 'parcels', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.drop_column('parcels', 'distributor_id')
    op.drop_column('parcels', 'customer_id')
    op.drop_column('parcels', 'estimated_delivery_date')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'brand_id')
    op.drop_column('orders', 'account_id')
    op.drop_column('orders', 'product_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'customer_id')
    op.drop_table('purchase_orders')
    op.drop_table('brand_products')
    op.drop_table('brand_contracts')
    # ### end Alembic commands ###
