"""empty message

Revision ID: 39bedace94ab
Revises: 1567e4425bf3
Create Date: 2021-11-21 15:31:44.679828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bedace94ab'
down_revision = '1567e4425bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_brand_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_brand_id_fkey', 'orders', 'customers', ['brand_id'], ['id'])
    # ### end Alembic commands ###
